---

firewalld_allow:
-
  port: 80/tcp
-
  port: 443/tcp

rvm1_rubies:
- 'ruby-2.2.3'
rvm1_user: 'vagrant'
rvm1_group: 'vagrant'
rvm1_temp_download_path: '/tmp'
rvm1_install_path: '/home/vagrant/.rvm'
rvm_install_gems:
- sinatra

### NGINX
nginx_permissions:
- vagrant

nginx_sites:
-
  file_name: "main"
  upstreams:
  - name: unicorn
    server: "unix:/var/run/unicorn/sockets/unicorn.sock fail_timeout=0"
  servers:
  -
    settings:
      server_name: dev.application.com
      listen: 80
    locations:
    -
      name: "/"
      access_log: "/var/log/nginx/access.log"
      error_log: "/var/log/nginx/error.log"
      proxy_pass: "http://unicorn/"
      proxy_set_header:
      - "X-Forwarded-For $proxy_add_x_forwarded_for"
      - "Host $http_host"
      - "X-Real-IP $remote_addr"
      sendfile: "off"
      proxy_redirect: "off"
      proxy_max_temp_file_size: "0"
      client_max_body_size: "10m"
      client_body_buffer_size: "128k"
      proxy_connect_timeout: "90"
      proxy_send_timeout: "90"
      proxy_read_timeout: "90"
      proxy_buffer_size: "4k"
      proxy_buffers: "4 32k"
      proxy_busy_buffers_size: "64k"
      proxy_temp_file_write_size: "64k"
